### ISSUE TITLE
![image](https://user-images.githubusercontent.com/43828836/97817345-148a0e80-1c9c-11eb-8c10-42a50aacef6c.png)

### ISSUE THREAD

**Issue by mnabywan** [kamsza/moral-dilema-detector#33]
![image](https://user-images.githubusercontent.com/43828836/97817345-148a0e80-1c9c-11eb-8c10-42a50aacef6c.png)

_Originally posted by @kbieniasz in https://github.com/kamsza/moral-dilema-detector/pull/32#issuecomment-720163494_

Tutaj takie niskie wyniki wyszły bo tak ustawiłeś filozofię?

**Comment by kbieniasz** [comment]
Zgadza się

**Comment by kbieniasz** [comment]
![image](https://user-images.githubusercontent.com/43828836/97902119-6898ff80-1d3d-11eb-9c8f-e418e2d55298.png)
![image](https://user-images.githubusercontent.com/43828836/97902140-7058a400-1d3d-11eb-8550-a924ba548b91.png)
Tutaj przykład dla innych wag
